[profile.default]
  optimizer = true
  solc = "0.8.25"
  via_ir = false

[rpc_endpoints]
  mainnet = "${MAINNET_RPC_URL}"
  optimism = "${OPTIMISM_RPC_URL}"
  optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}

[etherscan]
  mainnet = { key = "${MAINNET_ETHERSCAN_API_KEY}", chain = "mainnet" }
  optimism = { key = "${OPTIMISM_ETHERSCAN_API_KEY}", chain = "optimism" }
  mainnet = { key = "${OPTIMISM_SEPOLIA_ETHERSCAN_API_KEY}", chain = "optimism-sepolia" }

[fmt]
  bracket_spacing = false
  int_types = "long"
  line_length = 120
  multiline_func_header = "attributes_first"
  number_underscore = "thousands"
  quote_style = "double"
  single_line_statement_blocks = "single"
  tab_width = 2
  wrap_comments = true
